spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/institutDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

token:
  expiration:
    duration: 50000 # durée de 900 secondes (15 min)

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
